### ISSUE TITLE
Use unused ports

### ISSUE THREAD

**Issue by ChaosCoder** [KaneCheshire/Peasy#27]
As I don't control all the used ports on the system that runs the ui tests, it would be great to just use the next unused port and ask the server about the port it used. This would make parallel UI testing with one server per UI test more reliable.

E.g. usage like this:
```swift
let server = Server()
server.start(port: 0) // indicate we want to use a port the system chooses for us. Method name could be different.
let serverAddress = "http://localhost:\(server.port)" // Server needs a new property e.g. `var port: Int?` that gets set when start is called.

let app = XCUIApplication()
app.launchArguments.append(contentsOf: ["-SERVER_ADDRESS", serverAddress]) // use serverURL to pass to app as the server url
```

Is that possible?

**Comment by KaneCheshire** [comment]
I think this is sort of related to issue #1 and PR #20. I'm quite cautious to add anything where Peasy decides for you, as much as possible I want it to be you that tells Peasy what to do, rather than the other way around (like how you have to provide the port, and also how Peasy doesn't know how to respond to anything until you tell it).

I understand the need for this though. I feel like, if you could catch the error, you could then at least loop through the acceptable range of ports yourself until you don't get a port in use error, that way you'll know what port it is (because you're running in your own loop) and Peasy doesn't need to tell you what port it started on.

**Comment by ChaosCoder** [comment]
Please have a look at the PR, as actually the operating system already handles available ports for you. So Peasy can just report back, which port the system chose.
