### ISSUE TITLE
Question: building on Network.framework iOS 12+

### ISSUE THREAD

**Issue by iainsmith** [KaneCheshire/Peasy#31]
When you can drop iOS 11 support, I was thinking you might want to build on top of Network.framework (iOS 12+) or SwiftNIO to make it easier to get HTTPs support #13 

Links

* https://github.com/apple/swift-nio
* https://developer.apple.com/documentation/network

**Comment by KaneCheshire** [comment]
Peasy supports further back than iOS 11 because it's just using Darwin APIs rather than a specific framework. Peasy also supports running on tvOS, watchOS and macOS so using the Network framework would also mean those OSes would have to be limited to the recent ones as well.

If it makes it easier for HTTPs I'll definitely consider it, but it should also be possible without the use of that framework (which is likely just built on top of the same APIs Peasy already uses anyway)

Another downside of using Network would meant it would definitely limit it to Apple devices only, it wouldn't be a massive job to get Peasy working on Linux as it currently stands! Definitely have to weigh all this up.
